# Generated by Django 3.1.1 on 2020-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='text',
            field=models.TextField(default='Empty'),
        ),
    ]
